/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RunsRouteImport } from './routes/runs'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RunsIndexRouteImport } from './routes/runs.index'
import { Route as RunsIdRouteImport } from './routes/runs.$id'
import { Route as ChatIdRouteImport } from './routes/chat.$id'

const RunsRoute = RunsRouteImport.update({
  id: '/runs',
  path: '/runs',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RunsIndexRoute = RunsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RunsRoute,
} as any)
const RunsIdRoute = RunsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => RunsRoute,
} as any)
const ChatIdRoute = ChatIdRouteImport.update({
  id: '/chat/$id',
  path: '/chat/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/runs': typeof RunsRouteWithChildren
  '/chat/$id': typeof ChatIdRoute
  '/runs/$id': typeof RunsIdRoute
  '/runs/': typeof RunsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/chat/$id': typeof ChatIdRoute
  '/runs/$id': typeof RunsIdRoute
  '/runs': typeof RunsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/runs': typeof RunsRouteWithChildren
  '/chat/$id': typeof ChatIdRoute
  '/runs/$id': typeof RunsIdRoute
  '/runs/': typeof RunsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/runs'
    | '/chat/$id'
    | '/runs/$id'
    | '/runs/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/register' | '/chat/$id' | '/runs/$id' | '/runs'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/register'
    | '/runs'
    | '/chat/$id'
    | '/runs/$id'
    | '/runs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  RunsRoute: typeof RunsRouteWithChildren
  ChatIdRoute: typeof ChatIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/runs': {
      id: '/runs'
      path: '/runs'
      fullPath: '/runs'
      preLoaderRoute: typeof RunsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/runs/': {
      id: '/runs/'
      path: '/'
      fullPath: '/runs/'
      preLoaderRoute: typeof RunsIndexRouteImport
      parentRoute: typeof RunsRoute
    }
    '/runs/$id': {
      id: '/runs/$id'
      path: '/$id'
      fullPath: '/runs/$id'
      preLoaderRoute: typeof RunsIdRouteImport
      parentRoute: typeof RunsRoute
    }
    '/chat/$id': {
      id: '/chat/$id'
      path: '/chat/$id'
      fullPath: '/chat/$id'
      preLoaderRoute: typeof ChatIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface RunsRouteChildren {
  RunsIdRoute: typeof RunsIdRoute
  RunsIndexRoute: typeof RunsIndexRoute
}

const RunsRouteChildren: RunsRouteChildren = {
  RunsIdRoute: RunsIdRoute,
  RunsIndexRoute: RunsIndexRoute,
}

const RunsRouteWithChildren = RunsRoute._addFileChildren(RunsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  RunsRoute: RunsRouteWithChildren,
  ChatIdRoute: ChatIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
